kind: pipeline
type: exec
name: default

platform:
  os: darwin
  arch: amd64

steps:
  - name: test
    environment:
      USERNAME:
        from_secret: BROWSERSTACK_USERNAME
      PASSWORD:
        from_secret: BROWSERSTACK_ACCESS_KEY
    commands:
      - export PATH=/usr/bin:/bin:/usr/sbin:/sbin:/usr/local/bin:/usr/X11/bin:/opt/homebrew/Cellar/maven/3.8.1/bin:/opt/homebrew/Cellar/wget/1.21.3/bin
      - export BROWSERSTACK_USERNAME=$USERNAME
      - export BROWSERSTACK_ACCESS_KEY=$PASSWORD
      - wget "https://www.browserstack.com/browserstack-local/BrowserStackLocal-darwin-x64.zip"
      - unzip BrowserStackLocal-darwin-x64.zip
      - ./BrowserStackLocal --key $BROWSERSTACK_ACCESS_KEY --daemon start
      - mvn -Dtest=LocalTest test
      - ./BrowserStackLocal --key $BROWSERSTACK_ACCESS_KEY --daemon stop


trigger:
  branch:
    - main
  event:
    - push