kind: pipeline
type: exec
name: default

platform:
  os: darwin
  arch: amd64

steps:
  - name: test
    failure: ignore
    commands:
      - java -version
      - env
      - pwd
      - ls
      - ./gradlew bstack-single