kind: pipeline
type: exec
name: default

platform:
  os: darwin
  arch: amd64

trigger:
  event:
    - push

steps:
  - name: test
    environment:
      USERNAME:
        from_secret: BROWSERSTACK_USERNAME
      PASSWORD:
        from_secret: BROWSERSTACK_ACCESS_KEY
    commands:
      - export PATH=/opt/homebrew/Cellar/maven/3.8.1/bin
      - export BROWSERSTACK_USERNAME=$USERNAME
      - export BROWSERSTACK_ACCESS_KEY=$PASSWORD
      - mvn -Dtest=BrowserStackTest test