kind: pipeline
type: exec
name: default

platform:
  os: darwin
  arch: amd64

steps:
  - name: test
    commands:
      - java -version
      - export PATH=/usr/bin:/bin:/usr/sbin:/sbin:/usr/local/bin:/usr/X11/b‌​in
      - export JAVA_HOME=/Users/sujaysawant/Library/Java/JavaVirtualMachines/liberica-1.8.0_302
      - env
      - pwd
      - ls
      - ./gradlew bstack-single